platform :ios, '9.0'
use_frameworks!

pod 'SwiftKeychainWrapper'
pod 'CCBottomRefreshControl'
pod 'ReachabilitySwift'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Fabric'
pod 'Crashlytics'
pod 'SDWebImage', '~> 4.0'
target 'cellpex'

